hz1806axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^axf/", include("myaxf.urls", namespace="axf"))
]

myaxf/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r"^home$", home, name="home"),
    url(r"^market$", market, name="market"),
    url(r"^cart$", cart, name="cart"),
    url(r"^mine$", mine, name="mine"),
    url(r"^market_with_params/(\d+)/(\d+)/(\d+)",
        market_with_params,
        name="market_params"),
    url(r"^register$", RegisterAPI.as_view(), name="register"),
    url(r"^login$", LoginAPI.as_view(), name="login"),
    url(r"^logout$", LogoutAPI.as_view(), name="logout"),
    url(r"^confirm/(.*)", confirm),
    url(r"^check_uname$", check_uname),
    url(r"^cart_api$", CartAPI.as_view()),
    url(r"^cart_status", CartStatusAPI.as_view()),
    url(r"^cart_all_status$", CartAllStatusAPI.as_view()),
    url(r"^cart_item$", CartItemAPI.as_view()),
    url(r"^order$", OrderAPI.as_view(), name="order")
]

templates/market/market.html
{% extends 'base/base_main.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/market/css/market.css' %}">
{% endblock %}

{% block content %}
    <div id="market">
        <aside>
            <ul>

                {% for i in types %}
                    <li>
                        <a href="{% url 'axf:market_params' i.typeid '0' 0 %}">{{ i.typename }}</a>
{#                    判断是否是点击的那个分类#}
                    {% ifequal i.typeid  current_type_id %}
                        <span class="yellowSlide"></span>
                    {% endifequal %}
                    </li>
                {% endfor %}
            </ul>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span id="all_cate">
                            全部类型
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </span>
                    </li>
                    <li>
                        <span id="all_sort">
                            综合排序
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for i in goods %}
                        <li>
                            <a href="">
                                <img src="{{ i.productimg }}" alt="">
                                <div class="shoppingInfo">
                                    <h6>{{ i.productlongname }}</h6>
                                    <div class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </div>
                                    <p class="unit">
                                        {{ i.specifics }}
                                    </p>
                                    <p class="price">
                                        <span>￥{{ i.price }}</span>
                                        <s>￥{{ i.marketprice }}</s>
                                    </p>
                                </div>
                            </a>

                            <section>
                                <button class="subShopping" g_id="{{ i.id }}">-</button>
                                <span>{{ i.num }}</span>
                                <button class="addShopping" g_id="{{ i.id }}">+</button>
                            </section>
                        </li>
                    {% endfor %}

                </ul>
{#            全部分类的#}
            <div id="cates">
                <div>
{#                    <a href="">#}
{#                        <button>全部类型</button>#}
{#                    </a>#}
                    {% for i in sub_types %}
                        <a href="{% url 'axf:market_params' current_type_id i.1 0 %}">
{#                            <button>{{ i.0 }}</button>#}
                        {% if i.1 == current_sub_type_id %}
                            <button class="btn btn-success">{{ i.0 }}</button>
                            {% else %}
                            <button>{{ i.0 }}</button>
                        {% endif %}
                        </a>
                    {% endfor %}

                </div>
            </div>
{#            排序的#}
            <div id="sorts">
                <div>
                    <a href="{% url 'axf:market_params' current_type_id current_sub_type_id 0 %}">
{#                        <button>全部类型</button>#}
                        {% if order_type == 0 %}
                            <button class="btn btn-success">全部类型</button>
                            {% else %}
                            <button>全部类型</button>
                        {% endif %}
                    </a>
                    <a href="{% url 'axf:market_params' current_type_id current_sub_type_id 1 %}">
                        {% if order_type == 1 %}
                            <button class="btn btn-success">价格最低</button>
                            {% else %}
                            <button>价格最低</button>
                        {% endif %}
                    </a>
                    <a href="{% url 'axf:market_params' current_type_id current_sub_type_id 2 %}">

                        {% if order_type == 2 %}
                            <button class="btn btn-success">销量最高</button>
                            {% else %}
                            <button>销量最高</button>
                        {% endif %}
                    </a>
                </div>
            </div>
            </menu>
        </section>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/market/js/market.js' %}"></script>
{% endblock %}